### ISSUE TITLE
Question about the TE expression at the locus level

### ISSUE THREAD

**Issue by QianzhaoJ** [mhammell-laboratory/TElocal#23]
Hi,

Thanks for developing so helpful tools for  transposable element expression at different levels.
I have successfully run `TElocal`  to quantify transposable element expression  at the locus level, but I still fell confused about the output files.
The output of TElocal looks like raw read counts in different TE locus, but if I have multiple samples, with different sequencing depth, are these output files comparable to each other? Maybe I need some normalization for raw read counts? Is it feasible to use FPKM or TPM normlization? or DESeq2 rlog normlization?
Thanks in advance! 

Best wishes,
Qianzhao

**Comment by olivertam** [comment]
Hi Qianzhao,

Yes, the output is raw read counts in different TE locus. In order to compare between multiple samples, you will need to use a differential analysis software (e.g. DESeq2 or edgeR). What you would do is to join the individual `TElocal` output, and then feed it into DESeq2 or edgeR. They should be able to normalize the libraries (either ratio of medians or TMM) to do differential analysis. You can then do rlog/vst normalization if you want to visualize the data.

Hope this is helpful.

Thanks.

**Comment by QianzhaoJ** [comment]
I got it! Thank you for your prompt reply.
