### ISSUE TITLE
hs1 / t2t annotation table

### ISSUE THREAD

**Issue by maxfieldk** [mhammell-laboratory/TElocal#27]
Hi,
I am hoping to find an annotation table for the updated t2t hs1 human genome. Is this available?
Thank you!

**Comment by maxfieldk** [comment]
Thanks you for the super quick reply Oliver - your help is very much appreciated!
Cheers,
Maxfield

**Comment by maxfieldk** [comment]
Hi again Oliver,
Quick question - there wouldn't happen to be a version of this annotation table with strand information would there?
Thanks!

**Comment by olivertam** [comment]
Hi,

Thanks for your feedback.
We have now added the strand in the information as well. It should be at the same location.

Please let us know if you encounter more issues.

Thanks.

**Comment by maxfieldk** [comment]
Thanks Oliver this is great! I have one remaining question which is why are there some TEs in the index which appear multiple times with different locations?
For instance:
L1MD3_dup3562	chr1:27420-27496:-
L1MD3_dup3562	chr1:27537-27973:-
L1MD3_dup3562	chr1:27963-28052:-

Is this a software error or is the naming of each TE locus not necessarily unique?
Or perhaps would the above example represent an element with gaps, such that taking the min and max in the range will give you the 'full element'?
Thank you!

**Comment by olivertam** [comment]
Hi,

Thanks again for your feedback.
The T2T RepeatMasker track has "enhanced" annotations to give insight into "fragmented" TE loci. However, since we have typically "assumed" each exon is a separate instance (since that was the information provided by older RepeatMasker tracks), we do have these weird scenarios in the locations file.
So, theoretically, the L1MD3_dup3562 is predicted to be comprised of (at least) three "sections", so yes, you can get the min and max to give you the "full extent" of that element.
I'm not sure what is more useful
- Having the individual sections of a predicted instance listed separately
- Taking the min and max per instance as the "full element" (knowing that it could absorb other TE embedded within)
Thus, we've decided to keep it this way for now, and let users decide how best to interpret this.
Note that TElocal will treat all these "exons" are part of L1MD3_dup3562, and thus will assign reads to that instance if appropriate.

Thanks

**Comment by maxfieldk** [comment]
I see, oh what complications are entailed by RTEs!
Thanks Oliver, this cleared up a lot issues on my end. 
All the best,
Maxfield
