### ISSUE TITLE
T2T_CHM13_v2_rmsk_TE.gtf.locInd.locations

### ISSUE THREAD

**Issue by alha89** [mhammell-laboratory/TElocal#29]
Hi,

I am having trouble loading the link for the T2T locInd locations - I keep getting an out of memory error from the server.

Do you have this as a text file or similar that I could download instead?

Thank you

**Comment by olivertam** [comment]
Hi,

I am not seeing this issue myself, but I am now compressing those files so that transfer might be faster.
If you're still having issues, please let me know.
Here is the [link](https://labshare.cshl.edu/shares/mhammelllab/www-data/TElocal/annotation_tables/T2T_CHM13_v2_rmsk_TE.gtf.locInd.locations.gz).

Thanks.
