### ISSUE TITLE
Quantify signal at transposable elements from Pol2 ChIPseq or ATAC-seq

### ISSUE THREAD

**Issue by QianzhaoJ** [mhammell-laboratory/TElocal#53]
Thanks for developing so helpful tool !
I was trying to quantify signal at transposable elements from Pol2 ChIPseq and ATAC-seq.  
I guess that TElocal can do this. However, I only used TElocal on RNA-seq data before. 
Could you give me some suggestions for quantification on Pol2 ChIP-seq and ATAC-seq data using TElocal? such as  mapping or some specific parameters?

Best wishes
Qianzhao

**Comment by olivertam** [comment]
Hi,

I'm afraid that TElocal is not designed for ChIP/ATAC-seq data, as it's designed to look at the whole transcript, rather than discrete genomic regions (which is what you want for those datasets). Furthermore, many of the regions might not lie on the exonic portions of a gene (e.g. promoters), and thus would not be identified that way.
We would recommend using the standard workflows for those datasets, but perhaps allow for more genomic alignments per read (and not removing duplicates).

Thanks.
